name: Install Ansible
author: rishabhc32
branding:
  icon: package
  color: blue

description: Github Action to install Ansible

inputs:
  python-version:
    description: Python version to provision alongside uv (e.g., "3.12").
    required: false
    default: "3.12"
  ansible-package:
    description: 'The Ansible package spec to install. Allowed: "ansible" or "ansible==<version>" (e.g., "ansible==9.3.0").'
    required: false
    default: "ansible"
  uv-version:
    description: Version of uv to install (e.g., "latest", "0.7.13", ">=0.4.0"). Leave empty to use default resolution.
    required: false
    default: ""
  skip-setup-uv:
    description: Skip running setup-uv in this action. Set to "true" if you already ran setup-uv earlier in the job.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup uv and Python
      if: ${{ inputs.skip-setup-uv != 'true' }}
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: false
        version: ${{ inputs.uv-version }}

    - name: Install Ansible with uv tool
      id: install
      shell: bash
      run: |
        set -euo pipefail
        echo "uv version: $(uv --version)"
        echo "python version: $(python --version)"
        PKG_INPUT="${{ inputs.ansible-package }}"
        if [ -n "$PKG_INPUT" ]; then
          case "$PKG_INPUT" in
            ansible|ansible==*)
              PKG="$PKG_INPUT"
              ;;
            *)
              echo "Only 'ansible' or 'ansible==<version>' is allowed for 'ansible-package'. Got: $PKG_INPUT" >&2
              exit 1
              ;;
          esac
        else
          PKG="ansible"
        fi
        # Ensure the uv tool bin dir is on PATH for later steps
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        uv tool install "$PKG"

    - name: Verify installation
      shell: bash
      run: |
        set -euo pipefail
        if ! command -v ansible >/dev/null 2>&1; then
          echo "ansible executable not found on PATH after install" >&2
          exit 1
        fi
        ansible --version
        echo "ansible path: $(command -v ansible)"
